# Generated by Django 4.1.13 on 2024-07-31 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='category_id',
            new_name='category',
        ),
    ]
